DwaProject/DwaProject.WEB/Controllers/Admin/AdminVideoController.cs
using AutoMapper;
using DwaProject.BL.BLModels;
using DwaProject.BL.Repositories;
using DwaProject.WEB.Mapping;
using DwaProject.WEB.Viewmodels;
using Microsoft.AspNetCore.Mvc;

namespace DwaProject.WEB.Controllers.Admin
{
    public class AdminVideoController : Controller
	{
		private readonly IVideoRepository _videoRepository;
		private readonly IMapper _mapper;
		private readonly IImageRepository _imageRepository;
		private readonly IGenreRepository _genreRepository;
		private readonly ITagRepository _tagRepository;

		private VMFilter _filter = new VMFilter() { Page = 1, FilterName = "", TotalPages = 1, FilterType = "video"};

		public AdminVideoController(IVideoRepository videoRepository, IMapper mapper, ITagRepository tagRepository, IImageRepository imageRepository, IGenreRepository genreRepository)
		{
			_videoRepository = videoRepository;
			_mapper = mapper;
			_imageRepository = imageRepository;
			_genreRepository = genreRepository;
			_tagRepository = tagRepository;
		}



		// GET: VideoController
		public ActionResult Index()
		{
			//create the cookies
			CookieFetch();
			
            IEnumerable<BLVideo> blVideos;

			if(_filter.FilterType == "video")
				(blVideos, _filter.TotalPages) = _videoRepository.Search(_filter.FilterName, "name", "asc", _filter.Page, 5);
			else
			{
				(blVideos, _filter.TotalPages) = _videoRepository.SearchByGenreName(_filter.FilterName, _filter.Page, 5);
			}

			ViewData["Filter"] = _filter;

			var vmVideos = VMVideoMapper.MapToVM(blVideos).ToList();
			var blList = blVideos.ToList();
			

			//get genre
			for (int i = 0; i < vmVideos.Count; i++)
			{
				vmVideos[i].GenreName = _genreRepository.Get(blList[i].GenreId).Name;
			}

			return View(vmVideos);
		}

        private void CookieFetch()
        {
            var filterNameCookie = Request.Cookies["filterName"];
            var filterTypeCookie = Request.Cookies["filterType"];

            if (filterNameCookie != null && string.IsNullOrEmpty(_filter.FilterName))
                _filter.FilterName = filterNameCookie;

            if (filterTypeCookie != null && _filter.FilterType == "video")
                _filter.FilterType = filterTypeCookie;
        }

        public ActionResult VideoTableBodyPartial(int page)
        {
            _filter.Page = page;
			CookieFetch();

            IEnumerable<BLVideo> blVideos;

            if (_filter.FilterType == "video")
                (blVideos, _filter.TotalPages) = _videoRepository.Search(_filter.FilterName, "name", "asc", _filter.Page, 5);
            else
            {
                (blVideos, _filter.TotalPages) = _videoRepository.SearchByGenreName(_filter.FilterName, _filter.Page, 5);
            }

            ViewData["Filter"] = _filter;

            var vmVideos = VMVideoMapper.MapToVM(blVideos).ToList();
            var blList = blVideos.ToList();


            //get genre
            for (int i = 0; i < vmVideos.Count; i++)
            {
                vmVideos[i].GenreName = _genreRepository.Get(blList[i].GenreId).Name;
            }

            return PartialView("_VideoTableBodyPartial", vmVideos);
        }

		//Post: VideoController/Index
		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult Index(VMFilter filter)
		{
            filter.FilterName ??= "";

            //update the cookies
            Response.Cookies.Append("filterName", filter.FilterName);
			Response.Cookies.Append("filterType", filter.FilterType);
			
			if (_filter.FilterType != filter.FilterType || _filter.FilterName != filter.FilterName)
				_filter.Page = 1;
			else
				_filter.Page = filter.Page;

            _filter.FilterName = filter.FilterName;
            _filter.FilterType = filter.FilterType;

            return RedirectToAction("Index");
		}


		// GET: VideoController/Details/5
		public ActionResult Details(int id)
		{
            var blVideo = _videoRepository.Get(id);
            var video = VMVideoMapper.MapToVM(blVideo);
            video.GenreName = _genreRepository.Get(blVideo.GenreId).Name;
			
			BLImage blImage = _imageRepository.Get((int)blVideo.ImageId);
			VMImage vmImage = _mapper.Map<VMImage>(blImage);
			ViewData["Image"] = vmImage;

            return View(video);
		}

		// GET: VideoController/Create
		public ActionResult Create()
		{
            ViewData["Genres"] = _genreRepository.GetAll().ToList();
            ViewData["Images"] = _mapper.Map<List<VMImage>>(_imageRepository.GetAll().ToList());
			ViewData["Tags"] = _tagRepository.GetAll().ToList();

            return View();
		}

		// POST: VideoController/Create
		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult Create(VMVideo video)
		{
			try
			{
                //handle image
				if(video.ImageFile != null)
				{
                    var imageArray = GetFileByteAray(video.ImageFile);
                    if (imageArray != null)
                    {
						// To simplify things - we always add image
						VMImage vmImage = new VMImage()
						{
							Content = Convert.ToBase64String(imageArray)
						};
                        video.ImageId = _imageRepository.Post(_mapper.Map<BLImage>(vmImage));
                    }
                }
                else
					video.ImageId = (int)_imageRepository.GetAll().First(i => i.Content == video.ImageContent).Id!;
				
				var blVideo = VMVideoMapper.MapToBL(video);

                _videoRepository.Post(blVideo);

				return RedirectToAction(nameof(Index));
			}
			catch
			{
				return View();
			}
		}

		// GET: VideoController/Edit/5
		public ActionResult Edit(int id)
		{
			var blVideo = _videoRepository.Get(id);
            VMVideo videoToEdit = VMVideoMapper.MapToVM(blVideo);
            videoToEdit.GenreName = _genreRepository.Get(blVideo.GenreId).Name;

            ViewData["Genres"] = _genreRepository.GetAll().ToList();
			ViewData["Images"] = _mapper.Map<List<VMImage>>(_imageRepository.GetAll().ToList());
            ViewData["Tags"] = _tagRepository.GetAll().ToList();

            return View(videoToEdit);
		}

		// POST: VideoController/Edit/5
		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult Edit(int id, VMVideo video)
		{
			try
			{
                //handle image
                if (video.ImageFile != null)
                {
                    var imageArray = GetFileByteAray(video.ImageFile);
                    if (imageArray != null)
                    {
                        // To simplify things - we always add image
                        VMImage vmImage = new VMImage()
                        {
                            Content = Convert.ToBase64String(imageArray)
                        };
                        video.ImageId = _imageRepository.Post(_mapper.Map<BLImage>(vmImage));
                    }
                }
                else
                    video.ImageId = (int)_imageRepository.GetAll().First(i => i.Content == video.ImageContent).Id!;

                var blVideo = VMVideoMapper.MapToBL(video);

				_videoRepository.Post(id, blVideo);

				return RedirectToAction(nameof(Index));
			}
			catch
			{
				return View(video);
			}
		}

		// GET: VideoController/Delete/5
		public ActionResult Delete(int id)
		{
			var blVideo = _videoRepository.Get(id);
			var video = VMVideoMapper.MapToVM(blVideo);
            video.GenreName = _genreRepository.Get(blVideo.GenreId).Name;

            return View(video);
		}

		// POST: VideoController/Delete/5
		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult Delete(int id, VMVideo video)
		{
			try
			{
				_videoRepository.Delete(id);

				return RedirectToAction(nameof(Index));
			}
			catch
			{
				return View(video);
			}
		}

        private static byte[] GetFileByteAray(IFormFile formFile)
        {
            if (formFile != null)
            {
                if (formFile.Length > 0)
                {
                    using (var memoryStream = new MemoryStream())
                    {
                        formFile.CopyTo(memoryStream);

                        if (memoryStream.Length < 50 * 1024 * 1024)
                        {
                            return memoryStream.ToArray();
                        }
                    }

                }
            }

            return null;
        }
    }
}

DwaProject/DwaProject.WEB/Controllers/Public/UserController.cs
using AutoMapper;
using Azure.Core;
using DwaProject.BL.BLModels;
using DwaProject.BL.DALModels;
using DwaProject.BL.Repositories;
using DwaProject.WEB.Mapping;
using DwaProject.WEB.Viewmodels;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using NuGet.Protocol.Plugins;
using System.Security.Claims;
using System.Text;
using System.Web;

namespace DwaProject.WEB.Controllers.Public
{
    public class UserController : Controller
    {
        private readonly IMapper _mapper;
        private readonly IUserRepository _userRepository;
        private readonly IVideoRepository _videoRepository;
        private readonly IImageRepository _imageRepository;
        private readonly ICountryRepository _countryRepository;
        private readonly IHttpContextAccessor _httpContextAccessor;
        private readonly IGenreRepository _genreRepository;
        private readonly INotificationRepository _notificationRepository;
        private const string SUBJECT = "Validate your email";
        private const string LINK = "https://localhost:7291/api/users/ValidateEmail/";
        private const string BODY = "Validate your email by pressing this link: ";
        private VMFilter _filter = new VMFilter() { FilterName = "", Page = 1, TotalPages = 1 };

        public UserController(IMapper mapper, IUserRepository userRepository, IVideoRepository videoRepository,
            IImageRepository imageRepository, ICountryRepository countryRepository, IHttpContextAccessor httpContextAccessor, 
            IGenreRepository genreRepository, INotificationRepository notificationRepository)
        {
            _mapper = mapper;
            _userRepository = userRepository;
            _videoRepository = videoRepository;
            _imageRepository = imageRepository;
            _countryRepository = countryRepository;
            _httpContextAccessor = httpContextAccessor;
            _genreRepository = genreRepository;
            _notificationRepository = notificationRepository;
        }

        //GET
        [Authorize]
        public ActionResult Index(bool posted)
        {
            //create the cookies
            var filterNameCookie = Request.Cookies["filterNameVideo"];

            if(!posted)
            {
                if (filterNameCookie != null && string.IsNullOrEmpty(_filter.FilterName))
                    _filter.FilterName = filterNameCookie;
            }

            (var blVideos, _filter.TotalPages) = _videoRepository.Search(_filter.FilterName, "name", "asc", _filter.Page, 5);
            var vmVideos = VMVideoMapper.MapToVM(blVideos);

            ViewData["Filter"] = _filter;
            ViewData["Images"] = _mapper.Map<List<VMImage>>(_imageRepository.GetAll().ToList());


            return View(vmVideos.ToList());
        }

        public ActionResult VideoTableBodyPartial(int page)
        {
            _filter.Page = page;
            
            (var blVideos, _filter.TotalPages) = _videoRepository.Search(_filter.FilterName, "name", "asc", _filter.Page, 5);
            var vmVideos = VMVideoMapper.MapToVM(blVideos);

            ViewData["Filter"] = _filter;
            ViewData["Images"] = _mapper.Map<List<VMImage>>(_imageRepository.GetAll().ToList());


            return PartialView("_PublicVideoTableBodyPartial", vmVideos.ToList());
        }

        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Index(VMFilter filter)
        {
            filter.FilterName ??= "";

            //update the cookies
            Response.Cookies.Append("filterNameVideo", filter.FilterName);

            //if the filter changes, goes back to the first page
            if (_filter.FilterName != filter.FilterName)
                _filter.Page = 1;
            else
                _filter.Page = filter.Page;

            _filter.FilterName = filter.FilterName;

            return RedirectToAction(nameof(Index), true);
        }

        //GET
        [Authorize]
        public ActionResult Details(int id)
        {
            var blVideo = _videoRepository.Get(id);
            var vmVideo = VMVideoMapper.MapToVM(blVideo);

            vmVideo.GenreName = _genreRepository.Get(vmVideo.GenreId)!.Name;
            ViewData["Image"] = _mapper.Map<VMImage>(_imageRepository.Get(vmVideo.ImageId));

            return View(vmVideo);
        }


        //GET
        public ActionResult SelfRegister()
        {
            ViewData["Countries"] = _mapper.Map<List<VMCountry>>(_countryRepository.GetAll().ToList());
            return View();
        }

        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult SelfRegister(VMSelfRegister register)
        {
            if (!ModelState.IsValid)
                return View(register);

            try
            {
                var userRequest = VMRegisterMapper.MapToBL(register);
                var newUser = _userRepository.Register(userRequest);

                BLNotification notification = new BLNotification
                {
                    CreatedAt = DateTime.UtcNow,
                    ReceiverEmail = newUser.Email,
                    Subject = SUBJECT,
                    Body = BODY + LINK + HttpUtility.UrlEncode(newUser.Username) + "/" + HttpUtility.UrlEncode(newUser.SecurityToken)
                };


                notification = _notificationRepository.Post(notification);
                _notificationRepository.Send(notification);

                return RedirectToAction(nameof(Login));
            }
            catch(Exception ex)
            {
                ViewData["Countries"] = _mapper.Map<List<VMCountry>>(_countryRepository.GetAll().ToList());
                ModelState.AddModelError("Username", ex.Message);
                return View(register);
            }
            
        }

        //GET
        [HttpGet("api/users/ValidateEmail/{username}/{b64SecToken}")]
        public ActionResult ValidateEmail(VMValidateEmail validateEmail)
        {
            if (!ModelState.IsValid)
                return View(validateEmail);

            var request = _mapper.Map<ValidateEmailRequest>(validateEmail);

            _userRepository.ValidateEmail(request);

            return RedirectToAction(nameof(Login));
        }


        //GET
        public ActionResult Login()
        {
            return View();
        }

        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Login(VMLogin login)
        {
            if (!ModelState.IsValid)
                return View(login);

            var user = _userRepository.GetConfirmedUser(
                login.Username,
                login.Password);

            if (user == null)
            {
                ModelState.AddModelError("Username", "Invalid username or password");
                return View(login);
            }

            var claims = new List<Claim> { new Claim(ClaimTypes.Name, user.Username) };
            var claimsIdentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);
            HttpContext.SignInAsync(
                CookieAuthenticationDefaults.AuthenticationScheme,
                new ClaimsPrincipal(claimsIdentity),
                new AuthenticationProperties()).Wait();

            return RedirectToAction(nameof(Index));
        }


        //POST
        [HttpPost]
        [Authorize]
        public ActionResult Logout()
        {
            HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme).Wait();

            return RedirectToAction(nameof(Login));
        }


        //GET
        [Authorize]
        public ActionResult ChangePassword()
        {
            return View();
        }


        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ChangePassword(VMChangePassword changePassword)
        {
            var blChangePassword = _mapper.Map<BLChangePassword>(changePassword);

            if(!_userRepository.ChangePassword(blChangePassword))
            {
                ModelState.AddModelError("Username", "Invalid username or password");
                return View("ChangePassword");
            }
            

            return RedirectToAction(nameof(UserProfile));
        }

        //GET
        [Authorize]
        public ActionResult UserProfile()
        {
            var blUser = _userRepository.Get(_httpContextAccessor.HttpContext.User.FindFirst(ClaimTypes.Name)?.Value!);

            //it means no one is connected
            if (blUser == null)
                return RedirectToAction(nameof(Logout));

            var blCountries = _countryRepository.GetAll();
            var vmCountries = _mapper.Map<List<VMCountry>>(blCountries.ToList());
            ViewData["Countries"] = vmCountries;

            var vmUser = _mapper.Map<VMUser>(blUser);

            return View(vmUser);
        }
    }
}

DwaProject/DwaProject.WEB/Views/AdminVideo/Create.cshtml
@using DwaProject.BL.BLModels;
@using DwaProject.WEB.Viewmodels;
@model DwaProject.WEB.Viewmodels.VMVideo

@{
    ViewData["Title"] = "Create";
    List<BLGenre> _genres = ViewData["Genres"] as List<BLGenre>;
    List<VMImage> _images = ViewData["Images"] as List<VMImage>;
    List<BLTag> _tags = ViewData["Tags"] as List<BLTag>;
    string content = "";
}
<header>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="User" asp-action="Login">Mewvies</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div class="navbar-nav">
                    <a class="nav-link" asp-area="" asp-controller="AdminVideo" asp-action="Index">Videos</a>
                    <a class="nav-link" asp-area="" asp-controller="AdminCountry" asp-action="Index">Countries</a>
                    <a class="nav-link" asp-area="" asp-controller="AdminTag" asp-action="Index">Tags</a>
                    <a class="nav-link" asp-area="" asp-controller="AdminGenre" asp-action="Index">Genres</a>
                    <a class="nav-link" asp-area="" asp-controller="AdminUser" asp-action="Index">Users</a>
                </div>
            </div>
        </div>
    </nav>
</header>

<div class="container">
    <h1>Create</h1>

    <h4>Video</h4>
    <hr />
    <div class="row">
        <div class="col-md-4">
            <form asp-action="Create" enctype="multipart/form-data">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="Name" class="control-label"></label>
                    <input asp-for="Name" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Description" class="control-label"></label>
                    <input asp-for="Description" class="form-control" />
                    <span asp-validation-for="Description" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="GenreId" class="control-label">Genre</label>
                    <select asp-for="GenreId" class="form-control">
                        @foreach(var genre in _genres)
                        {
                            <option value="@genre.Id">@genre.Name</option>
                        }
                    </select>
                    <span asp-validation-for="GenreId" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="TotalSeconds" class="control-label"></label>
                    <input asp-for="TotalSeconds" class="form-control" min="1" default="120"/>
                    <span asp-validation-for="TotalSeconds" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="StreamingUrl" class="control-label"></label>
                    <input asp-for="StreamingUrl" class="form-control" />
                    <span asp-validation-for="StreamingUrl" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="ImageContent" class="control-label"></label>
                    <select id="imageSelect" asp-for="ImageContent" class="form-control" onchange="document.getElementById('imagePreview').src= 'data:image/png;base64,' + document.getElementById('imageSelect').value">
                        @foreach(var image in _images)
                        {
                            <option value="@image.Content">
                                @image.Id
                            </option>
                        }
                    </select>
                    <span asp-validation-for="ImageContent" class="text-danger"></span>
                    <br />
                    <img id="imagePreview" src="data:image/png;base64,@_images[0].Content" />
                </div>
                <div>
                    <label for="testFile">Or upload an image</label>
                    <input name="ImageFile" id="ImageFile" class="form-control" type="file" accept="image/*">
                </div>
                <div class="form-group">
                    <label asp-for="Tags" class="control-label"></label>
                    <select asp-for="Tags" class="form-control" multiple="multiple">
                        @foreach(var tag in _tags)
                        {
                            <option value="@tag.Name">@tag.Name</option>
                        }
                    </select>
                    <span asp-validation-for="Tags" class="text-danger"></span>
                </div>
                <br />
                <div class="form-group">
                    <input type="submit" value="Create" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>
    <br />
    <div>
        <a asp-action="Index" class="btn btn-info">Back to List</a>
    </div>

</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

DwaProject/DwaProject.WEB/Views/AdminVideo/Delete.cshtml
@model DwaProject.WEB.Viewmodels.VMVideo

@{
    ViewData["Title"] = "Delete";
}

<header>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="User" asp-action="Login">Mewvies</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div class="navbar-nav">
                    <a class="nav-link" asp-area="" asp-controller="AdminVideo" asp-action="Index">Videos</a>
                    <a class="nav-link" asp-area="" asp-controller="AdminCountry" asp-action="Index">Countries</a>
                    <a class="nav-link" asp-area="" asp-controller="AdminTag" asp-action="Index">Tags</a>
                    <a class="nav-link" asp-area="" asp-controller="AdminGenre" asp-action="Index">Genres</a>
                    <a class="nav-link" asp-area="" asp-controller="AdminUser" asp-action="Index">Users</a>
                </div>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <h1>Delete</h1>

    <h3>Are you sure you want to delete this?</h3>
    <div>
        <h4>Video</h4>
        <hr />
        <dl class="row">
        
            <dt class = "col-sm-2">
                @Html.DisplayNameFor(model => model.Name)
            </dt>
            <dd class = "col-sm-10">
                @Html.DisplayFor(model => model.Name)
            </dd>
            <dt class = "col-sm-2">
                @Html.DisplayNameFor(model => model.Description)
            </dt>
            <dd class = "col-sm-10">
                @Html.DisplayFor(model => model.Description)
            </dd>
            <dt class = "col-sm-2">
                Genre
            </dt>
            <dd class = "col-sm-10">
                @Html.DisplayFor(model => model.GenreId) :  @Html.DisplayFor(model => model.GenreName)
            </dd>
            <dt class = "col-sm-2">
                Duration
            </dt>
            <dd class = "col-sm-10">
                @Html.DisplayFor(model => model.TotalSeconds) s
            </dd>
            <dt class = "col-sm-2">
                Streaming Url
            </dt>
            <dd class = "col-sm-10">
                @Html.DisplayFor(model => model.StreamingUrl)
            </dd>
            <dt class = "col-sm-2">
                @Html.DisplayNameFor(model => model.ImageId)
            </dt>
            <dd class = "col-sm-10">
                @Html.DisplayFor(model => model.ImageId)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Tags)
            </dt>
            <dd class="col-sm-10">

                @{
                    string display = "";
                    int i = 0;

                    @for (; i < Model.Tags.Length - 1; i++)
                    {
                        display += Model.Tags[i] + ", ";
                    }
                    display += Model.Tags[i];
                }
                @display
                
            </dd>
        </dl>
        
        <br />
        <form asp-action="Delete">
            <input type="submit" value="Delete" class="btn btn-danger" /> |
            <a asp-action="Index" class="btn btn-info">Back to List</a>
        </form>
    </div>
</div>

DwaProject/DwaProject.WEB/Views/AdminVideo/Details.cshtml
@using DwaProject.WEB.Viewmodels;
@model DwaProject.WEB.Viewmodels.VMVideo

@{
    ViewData["Title"] = "Details";
    VMImage _image = ViewData["Image"] as VMImage;
}
<header>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="User" asp-action="Login">Mewvies</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div class="navbar-nav">
                    <a class="nav-link" asp-area="" asp-controller="AdminVideo" asp-action="Index">Videos</a>
                    <a class="nav-link" asp-area="" asp-controller="AdminCountry" asp-action="Index">Countries</a>
                    <a class="nav-link" asp-area="" asp-controller="AdminTag" asp-action="Index">Tags</a>
                    <a class="nav-link" asp-area="" asp-controller="AdminGenre" asp-action="Index">Genres</a>
                    <a class="nav-link" asp-area="" asp-controller="AdminUser" asp-action="Index">Users</a>
                </div>
            </div>
        </div>
    </nav>
</header>

<div class="container">
    <h1>Details</h1>

    <div>
        <h4>Video</h4>
        <hr />
        <dl class="row">
            <dt class = "col-sm-2">
                @Html.DisplayNameFor(model => model.Name)
            </dt>
            <dd class = "col-sm-10">
                @Html.DisplayFor(model => model.Name)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.ImageContent)
            </dt>
            <dd class="col-sm-10">
                <img src="data:image/png;base64,@_image!.Content" />
            </dd>
            <dt class = "col-sm-2">
                @Html.DisplayNameFor(model => model.Description)
            </dt>
            <dd class = "col-sm-10">
                @Html.DisplayFor(model => model.Description)
            </dd>
            <dt class = "col-sm-2">
                @Html.DisplayNameFor(model => model.GenreName)
            </dt>
            <dd class = "col-sm-10">
                @Html.DisplayFor(model => model.GenreId) : @Html.DisplayFor(model => model.GenreName)
            </dd>
            <dt class = "col-sm-2">
                @Html.DisplayNameFor(model => model.TotalSeconds)
            </dt>
            <dd class = "col-sm-10">
                @Html.DisplayFor(model => model.TotalSeconds) s
            </dd>
            <dt class = "col-sm-2">
                @Html.DisplayNameFor(model => model.StreamingUrl)
            </dt>
            <dd class = "col-sm-10">
                @Html.DisplayFor(model => model.StreamingUrl)
            </dd>
            
            
			<dt class="col-sm-2">
				@Html.DisplayNameFor(model => model.Tags)
			</dt>
			<dd class="col-sm-10">
                @{
                    string display = "";
                    int i = 0;

                    @for (; i < Model.Tags.Length - 1; i++)
                    {
                        display += Model.Tags[i] + ", ";
                    }
                    display += Model.Tags[i];
                }
                @display
			</dd>
        </dl>
    </div>
    <div>
        @Html.ActionLink("Edit", "Edit", new { id=Model.Id }, new { @class="btn btn-info"}) |
        @Html.ActionLink("Delete", "Delete", new {id=Model.Id }, new { @class="btn btn-danger"}) |
        <a asp-action="Index" class="btn btn-info">Back to List</a>
    </div>
</div>