DwaProject/DwaProject.WEB/Controllers/Admin/AdminCountryController.cs
using AutoMapper;
using DwaProject.BL.Repositories;
using DwaProject.WEB.Viewmodels;
using Microsoft.AspNetCore.Mvc;

namespace DwaProject.WEB.Controllers.Admin
{
    public class AdminCountryController : Controller
    {
        private readonly ICountryRepository _countryRepository;
        private readonly IMapper _mapper;
        private static VMFilter _filter = new VMFilter() { Page = 1, TotalPages = 1};
        public AdminCountryController(ICountryRepository countryRepo, IMapper mapper) 
        {
            _countryRepository = countryRepo;
            _mapper = mapper;
        }



        public ActionResult Index()
        {
            try
            {
                (var blCountries, _filter.TotalPages) = _countryRepository.GetAndPage(_filter.Page);


                var vmCountries = _mapper.Map<List<VMCountry>>(blCountries.ToList());

                ViewData["Filter"] = _filter;

                return View(vmCountries);
            }
            catch
            {
                return View();
            }

            
        }

        public ActionResult CountryTableBodyPartial(int page)
        {
            _filter.Page = page;
            (var blCountries, _filter.TotalPages) = _countryRepository.GetAndPage(_filter.Page);
            var vmCountries = _mapper.Map<List<VMCountry>>(blCountries.ToList());

            ViewData["Filter"] = _filter;

            return PartialView("_CountryTableBodyPartial", vmCountries);
        }

        
    }
}

DwaProject/DwaProject.WEB/Controllers/Admin/AdminUserController.cs
using AutoMapper;
using DwaProject.BL.BLModels;
using DwaProject.BL.Repositories;
using DwaProject.WEB.Viewmodels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.CodeAnalysis.VisualBasic.Syntax;
using System.Web;

namespace DwaProject.WEB.Controllers.Admin
{
    public class AdminUserController : Controller
    {
        private readonly IUserRepository _userRepository;
        private readonly IMapper _mapper;
        private readonly ICountryRepository _countryRepository;
        private readonly INotificationRepository _notificationRepository;
        private VMFilter _filter = new VMFilter() { FilterName = "", FilterType = "firstName", Page = 1, TotalPages = 1 };
        

        public AdminUserController(IUserRepository userRepository, IMapper mapper, ICountryRepository countryRepository, INotificationRepository notificationRepository)
        {
            _userRepository = userRepository;
            _mapper = mapper;
            _countryRepository = countryRepository;
            _notificationRepository = notificationRepository;
        }



        // GET: AdminUserController
        public ActionResult Index()
        {
            ViewData["Filter"] = _filter;

            //create the cookies
            CookieFetch();

            (var blUsers, _filter.TotalPages) = _userRepository.Search(_filter.FilterName, _filter.FilterType, _filter.Page);
            var vmUsers = _mapper.Map<List<VMUser>>(blUsers.ToList());

            return View(vmUsers);
        }

        public ActionResult UserTableBodyPartial(int page)
        {
            _filter.Page = page;
            CookieFetch();

            (var blUsers, _filter.TotalPages) = _userRepository.Search(_filter.FilterName, _filter.FilterType, _filter.Page);
            var vmUsers = _mapper.Map<List<VMUser>>(blUsers.ToList());

            ViewData["Filter"] = _filter;

            return PartialView("_UserTableBodyPartial", vmUsers);
        }

        private void CookieFetch()
        {
            var filterNameCookie = Request.Cookies["filterNameUser"];
            var filterTypeCookie = Request.Cookies["filterTypeUser"];
            if (filterNameCookie != null && string.IsNullOrEmpty(_filter.FilterName))
                _filter.FilterName = filterNameCookie;

            if (filterTypeCookie != null && _filter.FilterType == "firstName")
                _filter.FilterType = filterTypeCookie;
        }

        //POST: AdminuserController
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Index(VMFilter filter)
        {
            filter.FilterName ??= "";

            //update the cookies
            Response.Cookies.Append("filterNameUser", filter.FilterName);
            Response.Cookies.Append("filterTypeUser", filter.FilterType);

            //if the filter changes, goes back to the first page
            if (_filter.FilterType != filter.FilterType || _filter.FilterName != filter.FilterName)
                _filter.Page = 1;
            else
                _filter.Page = filter.Page;

            _filter.FilterName = filter.FilterName;
            _filter.FilterType = filter.FilterType;

            return RedirectToAction("Index");
        }

        // GET: AdminUserController/Details/5
        public ActionResult Details(int id)
        {
            var blUser = _userRepository.Get(id);
            var vmUser = _mapper.Map<VMUser>(blUser);

            ViewData["country"] = _mapper.Map<VMCountry>(_countryRepository.Get(vmUser.CountryOfResidenceId));

            return View(vmUser);
        }

        // GET: AdminUserController/Create
        public ActionResult Create()
        {
            var blCountries = _countryRepository.GetAll().ToList();
            var vmCountries = _mapper.Map<List<VMCountry>>(blCountries);
            ViewData["Country"] = vmCountries;

            return View();
        }

        // POST: AdminUserController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(UserRegisterRequest request)
        {
            try
            {
                var newUser = _userRepository.Register(request);
                var validateRequest = new ValidateEmailRequest()
                {
                    Username = newUser.Username,
                    B64SecToken = newUser.SecurityToken
                };
                _userRepository.ValidateEmail(validateRequest);

                return RedirectToAction(nameof(Index));
            }
            catch(Exception ex)
            {
                var blCountries = _countryRepository.GetAll().ToList();
                var vmCountries = _mapper.Map<List<VMCountry>>(blCountries);
                ViewData["Country"] = vmCountries;
                ModelState.AddModelError("Username", ex.Message);
                return View(request);
            }
        }

        // GET: AdminUserController/Edit/5
        public ActionResult Edit(int id)
        {
            var blCountries = _countryRepository.GetAll().ToList();
            var vmCountries = _mapper.Map<List<VMCountry>>(blCountries);
            ViewData["Country"] = vmCountries;

            var blUser = _userRepository.Get(id);
            var request = new UserRegisterRequest()
            {
                Username = blUser.Username,
                Email = blUser.Email,
                FirstName = blUser.FirstName,
                LastName = blUser.LastName,
                Phone = blUser.Phone,
                //no password written
                CountryOfResidenceId = blUser.CountryOfResidenceId
            };
            return View(request);
        }

        // POST: AdminUserController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, UserRegisterRequest request)
        {
            try
            {
                var user = _userRepository.Edit(id, request);

                return RedirectToAction(nameof(Index));
            }
            catch(Exception ex)
            {
                var blCountries = _countryRepository.GetAll().ToList();
                var vmCountries = _mapper.Map<List<VMCountry>>(blCountries);
                ViewData["Country"] = vmCountries;
                ModelState.AddModelError("Username", ex.Message);
                return View(request);
            }
        }

        // GET: AdminUserController/Delete/5
        public ActionResult Delete(int id)
        {
            var blUser = _userRepository.Get(id);
            var vmUser = _mapper.Map<VMUser>(blUser);

            return View(vmUser);
        }

        // POST: AdminUserController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, VMUser vmUser)
        {
            try
            {
                _userRepository.SoftDelete(id);

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View(vmUser);
            }
        }
    }
}

DwaProject/DwaProject.WEB/Controllers/Public/UserController.cs
using AutoMapper;
using Azure.Core;
using DwaProject.BL.BLModels;
using DwaProject.BL.DALModels;
using DwaProject.BL.Repositories;
using DwaProject.WEB.Mapping;
using DwaProject.WEB.Viewmodels;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using NuGet.Protocol.Plugins;
using System.Security.Claims;
using System.Text;
using System.Web;

namespace DwaProject.WEB.Controllers.Public
{
    public class UserController : Controller
    {
        private readonly IMapper _mapper;
        private readonly IUserRepository _userRepository;
        private readonly IVideoRepository _videoRepository;
        private readonly IImageRepository _imageRepository;
        private readonly ICountryRepository _countryRepository;
        private readonly IHttpContextAccessor _httpContextAccessor;
        private readonly IGenreRepository _genreRepository;
        private readonly INotificationRepository _notificationRepository;
        private const string SUBJECT = "Validate your email";
        private const string LINK = "https://localhost:7291/api/users/ValidateEmail/";
        private const string BODY = "Validate your email by pressing this link: ";
        private VMFilter _filter = new VMFilter() { FilterName = "", Page = 1, TotalPages = 1 };

        public UserController(IMapper mapper, IUserRepository userRepository, IVideoRepository videoRepository,
            IImageRepository imageRepository, ICountryRepository countryRepository, IHttpContextAccessor httpContextAccessor, 
            IGenreRepository genreRepository, INotificationRepository notificationRepository)
        {
            _mapper = mapper;
            _userRepository = userRepository;
            _videoRepository = videoRepository;
            _imageRepository = imageRepository;
            _countryRepository = countryRepository;
            _httpContextAccessor = httpContextAccessor;
            _genreRepository = genreRepository;
            _notificationRepository = notificationRepository;
        }

        //GET
        [Authorize]
        public ActionResult Index(bool posted)
        {
            //create the cookies
            var filterNameCookie = Request.Cookies["filterNameVideo"];

            if(!posted)
            {
                if (filterNameCookie != null && string.IsNullOrEmpty(_filter.FilterName))
                    _filter.FilterName = filterNameCookie;
            }

            (var blVideos, _filter.TotalPages) = _videoRepository.Search(_filter.FilterName, "name", "asc", _filter.Page, 5);
            var vmVideos = VMVideoMapper.MapToVM(blVideos);

            ViewData["Filter"] = _filter;
            ViewData["Images"] = _mapper.Map<List<VMImage>>(_imageRepository.GetAll().ToList());


            return View(vmVideos.ToList());
        }

        public ActionResult VideoTableBodyPartial(int page)
        {
            _filter.Page = page;
            
            (var blVideos, _filter.TotalPages) = _videoRepository.Search(_filter.FilterName, "name", "asc", _filter.Page, 5);
            var vmVideos = VMVideoMapper.MapToVM(blVideos);

            ViewData["Filter"] = _filter;
            ViewData["Images"] = _mapper.Map<List<VMImage>>(_imageRepository.GetAll().ToList());


            return PartialView("_PublicVideoTableBodyPartial", vmVideos.ToList());
        }

        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Index(VMFilter filter)
        {
            filter.FilterName ??= "";

            //update the cookies
            Response.Cookies.Append("filterNameVideo", filter.FilterName);

            //if the filter changes, goes back to the first page
            if (_filter.FilterName != filter.FilterName)
                _filter.Page = 1;
            else
                _filter.Page = filter.Page;

            _filter.FilterName = filter.FilterName;

            return RedirectToAction(nameof(Index), true);
        }

        //GET
        [Authorize]
        public ActionResult Details(int id)
        {
            var blVideo = _videoRepository.Get(id);
            var vmVideo = VMVideoMapper.MapToVM(blVideo);

            vmVideo.GenreName = _genreRepository.Get(vmVideo.GenreId)!.Name;
            ViewData["Image"] = _mapper.Map<VMImage>(_imageRepository.Get(vmVideo.ImageId));

            return View(vmVideo);
        }


        //GET
        public ActionResult SelfRegister()
        {
            ViewData["Countries"] = _mapper.Map<List<VMCountry>>(_countryRepository.GetAll().ToList());
            return View();
        }

        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult SelfRegister(VMSelfRegister register)
        {
            if (!ModelState.IsValid)
                return View(register);

            try
            {
                var userRequest = VMRegisterMapper.MapToBL(register);
                var newUser = _userRepository.Register(userRequest);

                BLNotification notification = new BLNotification
                {
                    CreatedAt = DateTime.UtcNow,
                    ReceiverEmail = newUser.Email,
                    Subject = SUBJECT,
                    Body = BODY + LINK + HttpUtility.UrlEncode(newUser.Username) + "/" + HttpUtility.UrlEncode(newUser.SecurityToken)
                };


                notification = _notificationRepository.Post(notification);
                _notificationRepository.Send(notification);

                return RedirectToAction(nameof(Login));
            }
            catch(Exception ex)
            {
                ViewData["Countries"] = _mapper.Map<List<VMCountry>>(_countryRepository.GetAll().ToList());
                ModelState.AddModelError("Username", ex.Message);
                return View(register);
            }
            
        }

        //GET
        [HttpGet("api/users/ValidateEmail/{username}/{b64SecToken}")]
        public ActionResult ValidateEmail(VMValidateEmail validateEmail)
        {
            if (!ModelState.IsValid)
                return View(validateEmail);

            var request = _mapper.Map<ValidateEmailRequest>(validateEmail);

            _userRepository.ValidateEmail(request);

            return RedirectToAction(nameof(Login));
        }


        //GET
        public ActionResult Login()
        {
            return View();
        }

        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Login(VMLogin login)
        {
            if (!ModelState.IsValid)
                return View(login);

            var user = _userRepository.GetConfirmedUser(
                login.Username,
                login.Password);

            if (user == null)
            {
                ModelState.AddModelError("Username", "Invalid username or password");
                return View(login);
            }

            var claims = new List<Claim> { new Claim(ClaimTypes.Name, user.Username) };
            var claimsIdentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);
            HttpContext.SignInAsync(
                CookieAuthenticationDefaults.AuthenticationScheme,
                new ClaimsPrincipal(claimsIdentity),
                new AuthenticationProperties()).Wait();

            return RedirectToAction(nameof(Index));
        }


        //POST
        [HttpPost]
        [Authorize]
        public ActionResult Logout()
        {
            HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme).Wait();

            return RedirectToAction(nameof(Login));
        }


        //GET
        [Authorize]
        public ActionResult ChangePassword()
        {
            return View();
        }


        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ChangePassword(VMChangePassword changePassword)
        {
            var blChangePassword = _mapper.Map<BLChangePassword>(changePassword);

            if(!_userRepository.ChangePassword(blChangePassword))
            {
                ModelState.AddModelError("Username", "Invalid username or password");
                return View("ChangePassword");
            }
            

            return RedirectToAction(nameof(UserProfile));
        }

        //GET
        [Authorize]
        public ActionResult UserProfile()
        {
            var blUser = _userRepository.Get(_httpContextAccessor.HttpContext.User.FindFirst(ClaimTypes.Name)?.Value!);

            //it means no one is connected
            if (blUser == null)
                return RedirectToAction(nameof(Logout));

            var blCountries = _countryRepository.GetAll();
            var vmCountries = _mapper.Map<List<VMCountry>>(blCountries.ToList());
            ViewData["Countries"] = vmCountries;

            var vmUser = _mapper.Map<VMUser>(blUser);

            return View(vmUser);
        }
    }
}

DwaProject/DwaProject.WEB/Views/AdminUser/Create.cshtml
@using DwaProject.WEB.Viewmodels;
@model DwaProject.BL.BLModels.UserRegisterRequest

@{
    ViewData["Title"] = "Create";
    List<VMCountry> _countries = ViewData["Country"] as List<VMCountry>;
}

<header>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="User" asp-action="Login">Mewvies</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div class="navbar-nav">
                    <a class="nav-link" asp-area="" asp-controller="AdminVideo" asp-action="Index">Videos</a>
                    <a class="nav-link" asp-area="" asp-controller="AdminCountry" asp-action="Index">Countries</a>
                    <a class="nav-link" asp-area="" asp-controller="AdminTag" asp-action="Index">Tags</a>
                    <a class="nav-link" asp-area="" asp-controller="AdminGenre" asp-action="Index">Genres</a>
                    <a class="nav-link" asp-area="" asp-controller="AdminUser" asp-action="Index">Users</a>
                </div>
            </div>
        </div>
    </nav>
</header>

<div class="container">
    <h1>Create</h1>

    <h4>User</h4>
    <hr />
    <div class="row">
        <div class="col-md-4">
            <form asp-action="Create">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="Username" class="control-label"></label>
                    <input asp-for="Username" class="form-control" />
                    <span asp-validation-for="Username" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="FirstName" class="control-label"></label>
                    <input asp-for="FirstName" class="form-control" />
                    <span asp-validation-for="FirstName" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="LastName" class="control-label"></label>
                    <input asp-for="LastName" class="form-control" />
                    <span asp-validation-for="LastName" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Password" class="control-label"></label>
                    <input type="password" asp-for="Password" class="form-control" />
                    <span asp-validation-for="Password" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Email" class="control-label"></label>
                    <input type="email" asp-for="Email" class="form-control" />
                    <span asp-validation-for="Email" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="CountryOfResidenceId" class="control-label"></label>
                    <select asp-for="CountryOfResidenceId" class="form-control">
                        @foreach(var country in _countries)
                        {
                            <option value="@country.Id">@country.Name</option>
                        }
                    </select>
                    <span asp-validation-for="CountryOfResidenceId" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Phone" class="control-label"></label>
                    <input asp-for="Phone" class="form-control" />
                    <span asp-validation-for="Phone" class="text-danger"></span>
                </div>
                <br />
                <div class="form-group">
                    <input type="submit" value="Create" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>
    <br />
    <div>
        <a asp-action="Index" class="btn btn-info">Back to List</a>
    </div>
</div>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

DwaProject/DwaProject.WEB/Views/AdminUser/Delete.cshtml
@using System.Net;
@model DwaProject.WEB.Viewmodels.VMUser

@{
    ViewData["Title"] = "Delete";
}

<header>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="User" asp-action="Login">Mewvies</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div class="navbar-nav">
                    <a class="nav-link" asp-area="" asp-controller="AdminVideo" asp-action="Index">Videos</a>
                    <a class="nav-link" asp-area="" asp-controller="AdminCountry" asp-action="Index">Countries</a>
                    <a class="nav-link" asp-area="" asp-controller="AdminTag" asp-action="Index">Tags</a>
                    <a class="nav-link" asp-area="" asp-controller="AdminGenre" asp-action="Index">Genres</a>
                    <a class="nav-link" asp-area="" asp-controller="AdminUser" asp-action="Index">Users</a>
                </div>
            </div>
        </div>
    </nav>
</header>
<br />
<div class="container">
    <h1>Deactivate</h1>

    <h3>Are you sure you want to deactivate this user?</h3>
    <div>
        <hr />
        <dl class="row">
            <dt class = "col-sm-2">
                @Html.DisplayNameFor(model => model.CreatedAt)
            </dt>
            <dd class = "col-sm-10">
                @Html.DisplayFor(model => model.CreatedAt)
            </dd>
            <dt class = "col-sm-2">
                @Html.DisplayNameFor(model => model.Username)
            </dt>
            <dd class = "col-sm-10">
                @Html.DisplayFor(model => model.Username)
            </dd>
            <dt class = "col-sm-2">
                @Html.DisplayNameFor(model => model.FirstName)
            </dt>
            <dd class = "col-sm-10">
                @Html.DisplayFor(model => model.FirstName)
            </dd>
            <dt class = "col-sm-2">
                @Html.DisplayNameFor(model => model.LastName)
            </dt>
            <dd class = "col-sm-10">
                @Html.DisplayFor(model => model.LastName)
            </dd>
            <dt class = "col-sm-2">
                @Html.DisplayNameFor(model => model.Email)
            </dt>
            <dd class = "col-sm-10">
                @Html.DisplayFor(model => model.Email)
            </dd>
            <dt class = "col-sm-2">
                @Html.DisplayNameFor(model => model.Phone)
            </dt>
            <dd class = "col-sm-10">
                @Html.DisplayFor(model => model.Phone)
            </dd>
            <dt class = "col-sm-2">
                @Html.DisplayNameFor(model => model.IsConfirmed)
            </dt>
            <dd class = "col-sm-10">
                @Html.DisplayFor(model => model.IsConfirmed)
            </dd>
            <dt class = "col-sm-2">
                @Html.DisplayNameFor(model => model.SecurityToken)
            </dt>
            <dd class = "col-sm-10">
                @WebUtility.UrlEncode(Model.SecurityToken);
            </dd>
            <dt class = "col-sm-2">
                @Html.DisplayNameFor(model => model.CountryOfResidenceId)
            </dt>
            <dd class = "col-sm-10">
                @Html.DisplayFor(model => model.CountryOfResidenceId)
            </dd>
        </dl>
    
        <form asp-action="Delete">
            <input type="submit" value="Deactivate" class="btn btn-danger" /> |
            <a asp-action="Index" class="btn btn-info">Back to List</a>
        </form>
    </div>
</div>

DwaProject/DwaProject.WEB/Views/AdminUser/Details.cshtml
@using System.Net;
@using DwaProject.WEB.Viewmodels;
@model DwaProject.WEB.Viewmodels.VMUser

@{
    ViewData["Title"] = "Details";
    VMCountry country = ViewData["country"] as VMCountry;
}
<header>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="User" asp-action="Login">Mewvies</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div class="navbar-nav">
                    <a class="nav-link" asp-area="" asp-controller="AdminVideo" asp-action="Index">Videos</a>
                    <a class="nav-link" asp-area="" asp-controller="AdminCountry" asp-action="Index">Countries</a>
                    <a class="nav-link" asp-area="" asp-controller="AdminTag" asp-action="Index">Tags</a>
                    <a class="nav-link" asp-area="" asp-controller="AdminGenre" asp-action="Index">Genres</a>
                    <a class="nav-link" asp-area="" asp-controller="AdminUser" asp-action="Index">Users</a>
                </div>
            </div>
        </div>
    </nav>
</header>

<div class="container">
    <h1>Details</h1>

    <div>
        <h4>User</h4>
        <hr />
        <dl class="row">
            <dt class = "col-sm-2">
                @Html.DisplayNameFor(model => model.CreatedAt)
            </dt>
            <dd class = "col-sm-10">
                @Html.DisplayFor(model => model.CreatedAt)
            </dd>
            <dt class = "col-sm-2">
                @Html.DisplayNameFor(model => model.Username)
            </dt>
            <dd class = "col-sm-10">
                @Html.DisplayFor(model => model.Username)
            </dd>
            <dt class = "col-sm-2">
                @Html.DisplayNameFor(model => model.FirstName)
            </dt>
            <dd class = "col-sm-10">
                @Html.DisplayFor(model => model.FirstName)
            </dd>
            <dt class = "col-sm-2">
                @Html.DisplayNameFor(model => model.LastName)
            </dt>
            <dd class = "col-sm-10">
                @Html.DisplayFor(model => model.LastName)
            </dd>
            <dt class = "col-sm-2">
                @Html.DisplayNameFor(model => model.Email)
            </dt>
            <dd class = "col-sm-10">
                @Html.DisplayFor(model => model.Email)
            </dd>
            <dt class = "col-sm-2">
                @Html.DisplayNameFor(model => model.Phone)
            </dt>
            <dd class = "col-sm-10">
                @Html.DisplayFor(model => model.Phone)
            </dd>
            <dt class = "col-sm-2">
                @Html.DisplayNameFor(model => model.IsConfirmed)
            </dt>
            <dd class = "col-sm-10">
                @Html.DisplayFor(model => model.IsConfirmed)
            </dd>
            <dt class = "col-sm-2">
                @Html.DisplayNameFor(model => model.SecurityToken)
            </dt>
            <dd class = "col-sm-10">
                @WebUtility.UrlEncode(Model.SecurityToken)
            </dd>
            <dt class = "col-sm-2">
                Country of residence:
            </dt>
            <dd class = "col-sm-10">
                @country.ToString()
            </dd>
        </dl>
    </div>
    <br />
    <div>
        @Html.ActionLink("Edit", "Edit", new { id=Model.Id }, new { @class="btn btn-info"}) |
        @Html.ActionLink("Deactivate", "Delete", new {id=Model.Id }, new { @class="btn btn-danger"}) |
        <a asp-action="Index" class="btn btn-info">Back to List</a>
    </div>
</div>

DwaProject/DwaProject.WEB/Views/AdminUser/_UserTableBodyPartial.cshtml
@using System.Net;
@using DwaProject.WEB.Viewmodels;
@model IEnumerable<DwaProject.WEB.Viewmodels.VMUser>

@{
    ViewData["Title"] = "Index";
    VMFilter _filter = ViewData["Filter"] as VMFilter;
}

@foreach (var item in Model)
{
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.CreatedAt)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Username)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FirstName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.LastName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Email)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Phone)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.IsConfirmed)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CountryOfResidenceId)
        </td>
        <td>
                    
            @Html.ActionLink("Details", "Details", new { id=item.Id }, new { @class="btn btn-secondary"})
        </td>
    </tr>
}