DwaProject/DwaProject.WEB/Controllers/Admin/AdminCountryController.cs
using AutoMapper;
using DwaProject.BL.Repositories;
using DwaProject.WEB.Viewmodels;
using Microsoft.AspNetCore.Mvc;

namespace DwaProject.WEB.Controllers.Admin
{
    public class AdminCountryController : Controller
    {
        private readonly ICountryRepository _countryRepository;
        private readonly IMapper _mapper;
        private static VMFilter _filter = new VMFilter() { Page = 1, TotalPages = 1};
        public AdminCountryController(ICountryRepository countryRepo, IMapper mapper) 
        {
            _countryRepository = countryRepo;
            _mapper = mapper;
        }



        public ActionResult Index()
        {
            try
            {
                (var blCountries, _filter.TotalPages) = _countryRepository.GetAndPage(_filter.Page);


                var vmCountries = _mapper.Map<List<VMCountry>>(blCountries.ToList());

                ViewData["Filter"] = _filter;

                return View(vmCountries);
            }
            catch
            {
                return View();
            }

            
        }

        public ActionResult CountryTableBodyPartial(int page)
        {
            _filter.Page = page;
            (var blCountries, _filter.TotalPages) = _countryRepository.GetAndPage(_filter.Page);
            var vmCountries = _mapper.Map<List<VMCountry>>(blCountries.ToList());

            ViewData["Filter"] = _filter;

            return PartialView("_CountryTableBodyPartial", vmCountries);
        }

        
    }
}

DwaProject/DwaProject.WEB/Controllers/Admin/AdminTagController.cs
using AutoMapper;
using DwaProject.BL.BLModels;
using DwaProject.BL.Repositories;
using DwaProject.WEB.Viewmodels;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace DwaProject.WEB.Controllers.Admin
{
    public class AdminTagController : Controller
    {
        private readonly IMapper _mapper;
        private readonly ITagRepository _tagRepository;
        private static VMFilter _filter = new VMFilter() { Page = 1, TotalPages = 1 };
        public AdminTagController(IMapper mapper, ITagRepository tagRepository) 
        {
            _mapper = mapper;
            _tagRepository = tagRepository;
        }

        // GET: AdminTagController
        public ActionResult Index()
        {
            (var blTag, _filter.TotalPages) = _tagRepository.GetAndPage(_filter.Page);
            var vmTag = _mapper.Map<List<VMTag>>(blTag.ToList());

            ViewData["Filter"] = _filter;

            return View(vmTag);
        }

        public ActionResult TagTableBodyPartial(int page)
        {
            _filter.Page = page;
            (var blTags, _filter.TotalPages) = _tagRepository.GetAndPage(_filter.Page);
            var vmTags = _mapper.Map<List<VMTag>>(blTags.ToList());

            ViewData["Filter"] = _filter;

            return PartialView("_TagTableBodyPartial", vmTags);
        }

        // GET: AdminTagController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: AdminTagController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(VMTag tag)
        {
            try
            {
                var blTag = _mapper.Map<BLTag>(tag);
                _tagRepository.Post(blTag);

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: AdminTagController/Edit/5
        public ActionResult Edit(int id)
        {
            var blTag = _tagRepository.Get(id);
            var vmTag = _mapper.Map<VMTag>(blTag);

            return View(vmTag);
        }

        // POST: AdminTagController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, VMTag tag)
        {
            try
            {
                var blTag = _mapper.Map<BLTag>(tag);
                _tagRepository.Post(id, blTag);

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View(tag);
            }
        }

        // GET: AdminTagController/Delete/5
        public ActionResult Delete(int id)
        {
            var blTag = _tagRepository.Get(id);
            var vmTag = _mapper.Map<VMTag>(blTag);

            return View(vmTag);
        }

        // POST: AdminTagController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, VMTag tag)
        {
            try
            {
                _tagRepository.Delete(id);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return RedirectToAction(nameof(DeleteError));
            }
        }

        public ActionResult DeleteError()
        {
            return View();
        }
    }
}

DwaProject/DwaProject.WEB/Controllers/Public/UserController.cs
using AutoMapper;
using Azure.Core;
using DwaProject.BL.BLModels;
using DwaProject.BL.DALModels;
using DwaProject.BL.Repositories;
using DwaProject.WEB.Mapping;
using DwaProject.WEB.Viewmodels;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using NuGet.Protocol.Plugins;
using System.Security.Claims;
using System.Text;
using System.Web;

namespace DwaProject.WEB.Controllers.Public
{
    public class UserController : Controller
    {
        private readonly IMapper _mapper;
        private readonly IUserRepository _userRepository;
        private readonly IVideoRepository _videoRepository;
        private readonly IImageRepository _imageRepository;
        private readonly ICountryRepository _countryRepository;
        private readonly IHttpContextAccessor _httpContextAccessor;
        private readonly IGenreRepository _genreRepository;
        private readonly INotificationRepository _notificationRepository;
        private const string SUBJECT = "Validate your email";
        private const string LINK = "https://localhost:7291/api/users/ValidateEmail/";
        private const string BODY = "Validate your email by pressing this link: ";
        private VMFilter _filter = new VMFilter() { FilterName = "", Page = 1, TotalPages = 1 };

        public UserController(IMapper mapper, IUserRepository userRepository, IVideoRepository videoRepository,
            IImageRepository imageRepository, ICountryRepository countryRepository, IHttpContextAccessor httpContextAccessor, 
            IGenreRepository genreRepository, INotificationRepository notificationRepository)
        {
            _mapper = mapper;
            _userRepository = userRepository;
            _videoRepository = videoRepository;
            _imageRepository = imageRepository;
            _countryRepository = countryRepository;
            _httpContextAccessor = httpContextAccessor;
            _genreRepository = genreRepository;
            _notificationRepository = notificationRepository;
        }

        //GET
        [Authorize]
        public ActionResult Index(bool posted)
        {
            //create the cookies
            var filterNameCookie = Request.Cookies["filterNameVideo"];

            if(!posted)
            {
                if (filterNameCookie != null && string.IsNullOrEmpty(_filter.FilterName))
                    _filter.FilterName = filterNameCookie;
            }

            (var blVideos, _filter.TotalPages) = _videoRepository.Search(_filter.FilterName, "name", "asc", _filter.Page, 5);
            var vmVideos = VMVideoMapper.MapToVM(blVideos);

            ViewData["Filter"] = _filter;
            ViewData["Images"] = _mapper.Map<List<VMImage>>(_imageRepository.GetAll().ToList());


            return View(vmVideos.ToList());
        }

        public ActionResult VideoTableBodyPartial(int page)
        {
            _filter.Page = page;
            
            (var blVideos, _filter.TotalPages) = _videoRepository.Search(_filter.FilterName, "name", "asc", _filter.Page, 5);
            var vmVideos = VMVideoMapper.MapToVM(blVideos);

            ViewData["Filter"] = _filter;
            ViewData["Images"] = _mapper.Map<List<VMImage>>(_imageRepository.GetAll().ToList());


            return PartialView("_PublicVideoTableBodyPartial", vmVideos.ToList());
        }

        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Index(VMFilter filter)
        {
            filter.FilterName ??= "";

            //update the cookies
            Response.Cookies.Append("filterNameVideo", filter.FilterName);

            //if the filter changes, goes back to the first page
            if (_filter.FilterName != filter.FilterName)
                _filter.Page = 1;
            else
                _filter.Page = filter.Page;

            _filter.FilterName = filter.FilterName;

            return RedirectToAction(nameof(Index), true);
        }

        //GET
        [Authorize]
        public ActionResult Details(int id)
        {
            var blVideo = _videoRepository.Get(id);
            var vmVideo = VMVideoMapper.MapToVM(blVideo);

            vmVideo.GenreName = _genreRepository.Get(vmVideo.GenreId)!.Name;
            ViewData["Image"] = _mapper.Map<VMImage>(_imageRepository.Get(vmVideo.ImageId));

            return View(vmVideo);
        }


        //GET
        public ActionResult SelfRegister()
        {
            ViewData["Countries"] = _mapper.Map<List<VMCountry>>(_countryRepository.GetAll().ToList());
            return View();
        }

        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult SelfRegister(VMSelfRegister register)
        {
            if (!ModelState.IsValid)
                return View(register);

            try
            {
                var userRequest = VMRegisterMapper.MapToBL(register);
                var newUser = _userRepository.Register(userRequest);

                BLNotification notification = new BLNotification
                {
                    CreatedAt = DateTime.UtcNow,
                    ReceiverEmail = newUser.Email,
                    Subject = SUBJECT,
                    Body = BODY + LINK + HttpUtility.UrlEncode(newUser.Username) + "/" + HttpUtility.UrlEncode(newUser.SecurityToken)
                };


                notification = _notificationRepository.Post(notification);
                _notificationRepository.Send(notification);

                return RedirectToAction(nameof(Login));
            }
            catch(Exception ex)
            {
                ViewData["Countries"] = _mapper.Map<List<VMCountry>>(_countryRepository.GetAll().ToList());
                ModelState.AddModelError("Username", ex.Message);
                return View(register);
            }
            
        }

        //GET
        [HttpGet("api/users/ValidateEmail/{username}/{b64SecToken}")]
        public ActionResult ValidateEmail(VMValidateEmail validateEmail)
        {
            if (!ModelState.IsValid)
                return View(validateEmail);

            var request = _mapper.Map<ValidateEmailRequest>(validateEmail);

            _userRepository.ValidateEmail(request);

            return RedirectToAction(nameof(Login));
        }


        //GET
        public ActionResult Login()
        {
            return View();
        }

        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Login(VMLogin login)
        {
            if (!ModelState.IsValid)
                return View(login);

            var user = _userRepository.GetConfirmedUser(
                login.Username,
                login.Password);

            if (user == null)
            {
                ModelState.AddModelError("Username", "Invalid username or password");
                return View(login);
            }

            var claims = new List<Claim> { new Claim(ClaimTypes.Name, user.Username) };
            var claimsIdentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);
            HttpContext.SignInAsync(
                CookieAuthenticationDefaults.AuthenticationScheme,
                new ClaimsPrincipal(claimsIdentity),
                new AuthenticationProperties()).Wait();

            return RedirectToAction(nameof(Index));
        }


        //POST
        [HttpPost]
        [Authorize]
        public ActionResult Logout()
        {
            HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme).Wait();

            return RedirectToAction(nameof(Login));
        }


        //GET
        [Authorize]
        public ActionResult ChangePassword()
        {
            return View();
        }


        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ChangePassword(VMChangePassword changePassword)
        {
            var blChangePassword = _mapper.Map<BLChangePassword>(changePassword);

            if(!_userRepository.ChangePassword(blChangePassword))
            {
                ModelState.AddModelError("Username", "Invalid username or password");
                return View("ChangePassword");
            }
            

            return RedirectToAction(nameof(UserProfile));
        }

        //GET
        [Authorize]
        public ActionResult UserProfile()
        {
            var blUser = _userRepository.Get(_httpContextAccessor.HttpContext.User.FindFirst(ClaimTypes.Name)?.Value!);

            //it means no one is connected
            if (blUser == null)
                return RedirectToAction(nameof(Logout));

            var blCountries = _countryRepository.GetAll();
            var vmCountries = _mapper.Map<List<VMCountry>>(blCountries.ToList());
            ViewData["Countries"] = vmCountries;

            var vmUser = _mapper.Map<VMUser>(blUser);

            return View(vmUser);
        }
    }
}

DwaProject/DwaProject.WEB/Views/AdminCountry/Index.cshtml
@using DwaProject.WEB.Viewmodels;
@model IEnumerable<DwaProject.WEB.Viewmodels.VMCountry>

@{
    ViewData["Title"] = "Index";
    VMFilter _filter = ViewData["Filter"] as VMFilter;
}
<header>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="User" asp-action="Login">Mewvies</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div class="navbar-nav">
                    <a class="nav-link" asp-area="" asp-controller="AdminVideo" asp-action="Index">Videos</a>
                    <a class="nav-link" asp-area="" asp-controller="AdminCountry" asp-action="Index">Countries</a>
                    <a class="nav-link" asp-area="" asp-controller="AdminTag" asp-action="Index">Tags</a>
                    <a class="nav-link" asp-area="" asp-controller="AdminGenre" asp-action="Index">Genres</a>
                    <a class="nav-link" asp-area="" asp-controller="AdminUser" asp-action="Index">Users</a>
                </div>
            </div>
        </div>
    </nav>
</header>
<br />
<div class="container">
    <label>Page:</label><br/>
    <div class="btn-group">
        @for (var i = 1; i <= _filter!.TotalPages; i++)
        {
            var currClass = _filter.Page == i ? "btn-primary" : "btn-outline-primary";
            <a asp-action="Index"
               data-page="@i"
               class="pager-btn btn @currClass">@i</a>
        }
    </div>

    <br />
    <h1>Countries</h1>

    
    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Code)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Name)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody id="country-table-body">
            <partial name="_CountryTableBodyPartial" />
        </tbody>
    </table>
</div>

@section Scripts {
    <script>
        $(".pager-btn").click(function (event) {
            console.log("Pager button clicked");
            event.preventDefault();

            var page = $(this).data("page");

            var ajaxData = {
                page: page
            };

            $.ajax({
                type: "GET",
                url: "/AdminCountry/CountryTableBodyPartial",
                data: ajaxData,
                success: function (data) {
                    $("#country-table-body").html(data);

                    $(".pager-btn").removeClass("btn-primary");
                    $(".pager-btn").addClass("btn-outline-primary");

                    $(".pager-btn[data-page=" + page + "]").removeClass("btn-outline-primary");
                    $(".pager-btn[data-page=" + page + "]").addClass("btn-primary");
                },
                error: function (data) {
                    console.error("Ajax GET error", data);
                }
            });
        });
    </script>
}

DwaProject/DwaProject.WEB/Views/AdminCountry/_CountryTableBodyPartial.cshtml
@using DwaProject.WEB.Viewmodels;
@model IEnumerable<DwaProject.WEB.Viewmodels.VMCountry>

@foreach (var item in Model)
{
    <tr>
        <td>
            @Html.HiddenFor(modelItem => item.Id)
            @Html.DisplayFor(modelItem => item.Code)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
    </tr>
}